/**
 * Demo Mode Mock Data
 * Used when Supabase is not configured
 */

import type { Applicant, AdminUser, Communication, CalendarEvent, AutomationRule, MessageTemplate } from '@/types/database'

export const isDemoMode = !process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

export const mockAdmin: AdminUser = {
  id: 'demo-admin-123',
  email: 'admin@demo.com',
  name: 'Demo Admin',
  role: 'admin',
  created_at: new Date().toISOString(),
}

export const mockApplicants: Applicant[] = [
  {
    id: 'app-001',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    first_name: 'John',
    last_name: 'Smith',
    email: 'john.smith@email.com',
    phone: '(555) 123-4567',
    sms_opt_in: true,
    lead_source: 'Website',
    referral_code: null,
    has_cdl: true,
    has_medical_card: true,
    experience_months: 24,
    location_state: 'Texas',
    us_work_eligible: true,
    is_prequalified: true,
    disqualification_reason: null,
    status: 'new',
    ownership_goal: 'Full ownership within 2 years',
    truck_preference: 'Freightliner Cascadia',
    freight_preference: 'OTR',
    has_existing_carrier: false,
    carrier_name: null,
    notes: 'Very motivated, has savings for down payment',
    assigned_to: null,
    form_step: 4,
    is_complete: true,
    last_contacted_at: null,
    last_response_at: null,
    automation_paused: false,
    preferred_contact_channel: 'email',
  },
  {
    id: 'app-002',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    first_name: 'Maria',
    last_name: 'Garcia',
    email: 'maria.garcia@email.com',
    phone: '(555) 234-5678',
    sms_opt_in: true,
    lead_source: 'Referral',
    referral_code: 'REF123',
    has_cdl: true,
    has_medical_card: true,
    experience_months: 36,
    location_state: 'California',
    us_work_eligible: true,
    is_prequalified: true,
    disqualification_reason: null,
    status: 'in_progress',
    ownership_goal: 'Build a small fleet',
    truck_preference: 'Peterbilt 579',
    freight_preference: 'Regional',
    has_existing_carrier: true,
    carrier_name: 'Swift Transportation',
    notes: 'Currently with Swift, looking to become owner-op',
    assigned_to: null,
    form_step: 4,
    is_complete: true,
    last_contacted_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    last_response_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    automation_paused: false,
    preferred_contact_channel: 'sms',
  },
  {
    id: 'app-003',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    first_name: 'Robert',
    last_name: 'Johnson',
    email: 'robert.j@email.com',
    phone: '(555) 345-6789',
    sms_opt_in: false,
    lead_source: 'Facebook',
    referral_code: null,
    has_cdl: true,
    has_medical_card: true,
    experience_months: 48,
    location_state: 'Florida',
    us_work_eligible: true,
    is_prequalified: true,
    disqualification_reason: null,
    status: 'carrier_app',
    ownership_goal: 'Become independent contractor',
    truck_preference: 'Kenworth T680',
    freight_preference: 'Dedicated',
    has_existing_carrier: false,
    carrier_name: null,
    notes: 'Submitted carrier application to XPO',
    assigned_to: null,
    form_step: 4,
    is_complete: true,
    last_contacted_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    last_response_at: null,
    automation_paused: true,
    preferred_contact_channel: 'email',
  },
  {
    id: 'app-004',
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    first_name: 'Sarah',
    last_name: 'Williams',
    email: 'sarah.w@email.com',
    phone: '(555) 456-7890',
    sms_opt_in: true,
    lead_source: 'Google',
    referral_code: null,
    has_cdl: true,
    has_medical_card: true,
    experience_months: 18,
    location_state: 'Georgia',
    us_work_eligible: true,
    is_prequalified: true,
    disqualification_reason: null,
    status: 'pending',
    ownership_goal: 'Team driving with spouse',
    truck_preference: 'Volvo VNL',
    freight_preference: 'OTR',
    has_existing_carrier: false,
    carrier_name: null,
    notes: 'Waiting on carrier approval',
    assigned_to: null,
    form_step: 4,
    is_complete: true,
    last_contacted_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    last_response_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    automation_paused: false,
    preferred_contact_channel: 'email',
  },
  {
    id: 'app-005',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    first_name: 'Michael',
    last_name: 'Brown',
    email: 'mike.brown@email.com',
    phone: '(555) 567-8901',
    sms_opt_in: true,
    lead_source: 'Website',
    referral_code: null,
    has_cdl: true,
    has_medical_card: true,
    experience_months: 60,
    location_state: 'Ohio',
    us_work_eligible: true,
    is_prequalified: true,
    disqualification_reason: null,
    status: 'complete',
    ownership_goal: 'Already driving own truck',
    truck_preference: 'Freightliner Cascadia',
    freight_preference: 'Dedicated',
    has_existing_carrier: true,
    carrier_name: 'Landstar',
    notes: 'Successfully matched and driving!',
    assigned_to: null,
    form_step: 4,
    is_complete: true,
    last_contacted_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    last_response_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    automation_paused: true,
    preferred_contact_channel: 'email',
  },
  {
    id: 'app-006',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    first_name: 'David',
    last_name: 'Lee',
    email: 'david.lee@email.com',
    phone: '(555) 678-9012',
    sms_opt_in: false,
    lead_source: 'Instagram',
    referral_code: null,
    has_cdl: false,
    has_medical_card: true,
    experience_months: 6,
    location_state: 'Arizona',
    us_work_eligible: true,
    is_prequalified: false,
    disqualification_reason: 'No CDL-A license',
    status: 'disqualified',
    ownership_goal: 'Get CDL first, then lease',
    truck_preference: null,
    freight_preference: null,
    has_existing_carrier: false,
    carrier_name: null,
    notes: 'Encouraged to get CDL and reapply',
    assigned_to: null,
    form_step: 2,
    is_complete: false,
    last_contacted_at: null,
    last_response_at: null,
    automation_paused: true,
    preferred_contact_channel: 'email',
  },
]

export const mockCommunications: Communication[] = [
  {
    id: 'comm-001',
    applicant_id: 'app-001',
    admin_user_id: 'demo-admin-123',
    channel: 'email',
    direction: 'outbound',
    subject: 'Welcome to High Road Capital!',
    body: 'Hi John, Thank you for applying to our lease-to-own program...',
    status: 'delivered',
    template_id: null,
    is_automated: true,
    external_id: 'msg_123',
    sent_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    delivered_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    failed_reason: null,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'comm-002',
    applicant_id: 'app-002',
    admin_user_id: 'demo-admin-123',
    channel: 'sms',
    direction: 'outbound',
    subject: null,
    body: 'Hi Maria, just checking in on your application. Any questions?',
    status: 'delivered',
    template_id: null,
    is_automated: false,
    external_id: 'sms_456',
    sent_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    delivered_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    failed_reason: null,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: 'event-001',
    admin_user_id: 'demo-admin-123',
    applicant_id: 'app-001',
    title: 'Call with John Smith',
    description: 'Intro call to discuss program',
    event_type: 'call',
    starts_at: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    ends_at: new Date(Date.now() + 2.5 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    reminder_sent: false,
    meeting_link: null,
    phone_number: '(555) 123-4567',
    notes: null,
    booking_token: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'event-002',
    admin_user_id: 'demo-admin-123',
    applicant_id: 'app-002',
    title: 'Follow-up with Maria Garcia',
    description: 'Discuss carrier options',
    event_type: 'call',
    starts_at: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(),
    ends_at: new Date(Date.now() + 26.5 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    reminder_sent: false,
    meeting_link: null,
    phone_number: '(555) 234-5678',
    notes: 'She prefers afternoon calls',
    booking_token: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockAvailability = [
  { id: 'avail-0', admin_user_id: 'demo-admin-123', day_of_week: 0, start_time: '09:00', end_time: '17:00', is_active: false, timezone: 'America/New_York', created_at: new Date().toISOString() },
  { id: 'avail-1', admin_user_id: 'demo-admin-123', day_of_week: 1, start_time: '09:00', end_time: '17:00', is_active: true, timezone: 'America/New_York', created_at: new Date().toISOString() },
  { id: 'avail-2', admin_user_id: 'demo-admin-123', day_of_week: 2, start_time: '09:00', end_time: '17:00', is_active: true, timezone: 'America/New_York', created_at: new Date().toISOString() },
  { id: 'avail-3', admin_user_id: 'demo-admin-123', day_of_week: 3, start_time: '09:00', end_time: '17:00', is_active: true, timezone: 'America/New_York', created_at: new Date().toISOString() },
  { id: 'avail-4', admin_user_id: 'demo-admin-123', day_of_week: 4, start_time: '09:00', end_time: '17:00', is_active: true, timezone: 'America/New_York', created_at: new Date().toISOString() },
  { id: 'avail-5', admin_user_id: 'demo-admin-123', day_of_week: 5, start_time: '09:00', end_time: '15:00', is_active: true, timezone: 'America/New_York', created_at: new Date().toISOString() },
  { id: 'avail-6', admin_user_id: 'demo-admin-123', day_of_week: 6, start_time: '09:00', end_time: '17:00', is_active: false, timezone: 'America/New_York', created_at: new Date().toISOString() },
]

export const mockAutomationRules: AutomationRule[] = [
  {
    id: 'auto-001',
    name: 'New Application Welcome',
    description: 'Send welcome email immediately when application is submitted',
    trigger_type: 'status_change',
    trigger_status: 'new',
    trigger_days: null,
    action_template_id: null,
    action_channel: 'email',
    stop_on_response: false,
    stop_on_status_change: false,
    max_sends: 1,
    delay_minutes: 0,
    is_active: true,
    priority: 10,
    created_by: 'demo-admin-123',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'auto-002',
    name: 'Day 3 Check-in',
    description: 'Send follow-up email 3 days after application if no response',
    trigger_type: 'days_in_status',
    trigger_status: 'new',
    trigger_days: 3,
    action_template_id: null,
    action_channel: 'email',
    stop_on_response: true,
    stop_on_status_change: true,
    max_sends: 1,
    delay_minutes: 0,
    is_active: true,
    priority: 5,
    created_by: 'demo-admin-123',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'auto-003',
    name: 'Day 7 SMS Reminder',
    description: 'Send SMS reminder 7 days after application if still no response',
    trigger_type: 'days_in_status',
    trigger_status: 'new',
    trigger_days: 7,
    action_template_id: null,
    action_channel: 'sms',
    stop_on_response: true,
    stop_on_status_change: true,
    max_sends: 1,
    delay_minutes: 0,
    is_active: true,
    priority: 3,
    created_by: 'demo-admin-123',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'auto-004',
    name: 'Document Reminder',
    description: 'Remind about missing documents after 5 days',
    trigger_type: 'missing_documents',
    trigger_status: null,
    trigger_days: 5,
    action_template_id: null,
    action_channel: 'email',
    stop_on_response: true,
    stop_on_status_change: false,
    max_sends: 3,
    delay_minutes: 0,
    is_active: false,
    priority: 2,
    created_by: 'demo-admin-123',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockTemplates: MessageTemplate[] = [
  {
    id: 'tmpl-001',
    name: 'Welcome Email',
    channel: 'email',
    category: 'welcome',
    subject: 'Welcome to High Road Capital!',
    body: 'Hi {{first_name}},\n\nThank you for applying to our lease-to-own program! We\'re excited to help you start your journey to truck ownership.\n\nBest regards,\nHigh Road Capital Team',
    variables: ['first_name'],
    is_active: true,
    created_by: 'demo-admin-123',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tmpl-002',
    name: 'Document Request',
    channel: 'email',
    category: 'document_request',
    subject: 'Documents Needed - High Road Capital',
    body: 'Hi {{first_name}},\n\nTo move forward with your application, we need:\n\n• CDL (front and back)\n• Medical Card\n• MVR Report\n\nPlease upload these at your earliest convenience.\n\nBest,\n{{admin_name}}',
    variables: ['first_name', 'admin_name'],
    is_active: true,
    created_by: 'demo-admin-123',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tmpl-003',
    name: 'Follow-up Check-in',
    channel: 'email',
    category: 'follow_up',
    subject: 'Checking In - High Road Capital',
    body: 'Hi {{first_name}},\n\nI wanted to check in and see how things are going. Is there anything I can help with?\n\nBest,\n{{admin_name}}',
    variables: ['first_name', 'admin_name'],
    is_active: true,
    created_by: 'demo-admin-123',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tmpl-004',
    name: 'SMS Welcome',
    channel: 'sms',
    category: 'welcome',
    subject: null,
    body: 'Hi {{first_name}}! Thanks for applying to High Road Capital. We received your application and will be in touch soon. Reply STOP to opt out.',
    variables: ['first_name'],
    is_active: true,
    created_by: 'demo-admin-123',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Dashboard stats
export const mockStats = {
  total_applicants: mockApplicants.length,
  new_this_week: 2,
  in_progress: mockApplicants.filter(a => a.status === 'in_progress').length,
  prequalified: mockApplicants.filter(a => a.is_prequalified).length,
  completed: mockApplicants.filter(a => a.status === 'complete').length,
}
